[tool.poetry]
name = "sessionmon"
version = "0.1.0"
description = ""
authors = ["Tony <tony@tonykirkland.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dbus-python = "^1.3.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
